import '../../../../node_modules/mathjax-full/components/src/startup/lib/startup.js';
import '../../../../node_modules/mathjax-full/components/src/tex-mml-svg/preload.js';
import '../../../../node_modules/mathjax-full/components/src/core/core.js';
import '../../../../node_modules/mathjax-full/components/src/input/tex/tex.js';
import '../../../../node_modules/mathjax-full/components/src/input/mml/mml.js';
import '../../../../node_modules/mathjax-full/components/src/output/svg/svg.js';
import '../../../../node_modules/mathjax-full/components/src/output/svg/fonts/tex/tex.js';
import '../../../../node_modules/mathjax-full/components/src/ui/menu/menu.js';
import {CONFIG} from '../../../../node_modules/mathjax-full/js/components/loader.js';
CONFIG.ready();
